//! End-to-end TLS decryption tests against real captured sessions.
//!
//! Unlike the in-crate unit tests (which drive the crypto with synthetic
//! known-answer vectors), these run the built binary against real TLS
//! handshakes captured on loopback, decrypt them with the session's
//! SSLKEYLOGFILE, and grep a marker string that exists ONLY inside the
//! encrypted payload. That proves the whole pipeline — capture parsing,
//! stream reassembly, key derivation, record decryption — not just the
//! primitives.
//!
//! Fixtures live in `tests/fixtures/` and are regenerated by
//! `tests/fixtures/generate.sh`. Each is a throwaway localhost session to a
//! self-signed cert, so the committed keylogs protect nothing.

use std::path::PathBuf;
use std::process::Command;

fn netgrep() -> Command {
    Command::new(env!("CARGO_BIN_EXE_netgrep"))
}

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Decrypt `pcap` with `keylog` and return whether `marker` was found in the
/// decrypted output (stdout carries matched payloads).
fn decrypts_to(pcap: &str, keylog: &str, marker: &str) -> bool {
    let out = netgrep()
        .arg("--keylog")
        .arg(fixture(keylog))
        .arg("-I")
        .arg(fixture(pcap))
        .arg(marker)
        .output()
        .expect("failed to run netgrep");
    assert!(
        out.status.success(),
        "netgrep exited unsuccessfully: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout).contains(marker)
}

#[test]
fn decrypts_real_tls13_session() {
    assert!(
        decrypts_to(
            "tls13_aesgcm.pcap",
            "tls13_aesgcm.keys",
            "netgrep-tls13-marker-7Qx"
        ),
        "TLS 1.3 AES-GCM session should decrypt and expose the request marker"
    );
}

#[test]
fn decrypts_real_tls12_session() {
    // Regression guard for the ServerHello-negotiation fix: this capture is a
    // client that offered TLS 1.3 but was negotiated down to 1.2 by the server
    // — the real-world shape that failed to decrypt before the fix.
    assert!(
        decrypts_to(
            "tls12_ecdhe_rsa_aesgcm.pcap",
            "tls12_ecdhe_rsa_aesgcm.keys",
            "netgrep-tls12-marker-4Rk"
        ),
        "TLS 1.2 ECDHE-RSA-AES128-GCM session should decrypt and expose the request marker"
    );
}

#[test]
fn marker_is_genuinely_encrypted() {
    // Negative control: without the keylog the marker must NOT appear, proving
    // the positive tests above are decrypting rather than matching cleartext.
    let out = netgrep()
        .arg("-I")
        .arg(fixture("tls12_ecdhe_rsa_aesgcm.pcap"))
        .arg("netgrep-tls12-marker-4Rk")
        .output()
        .expect("failed to run netgrep");
    assert!(out.status.success());
    assert!(
        !String::from_utf8_lossy(&out.stdout).contains("netgrep-tls12-marker-4Rk"),
        "marker must be encrypted — it should not be visible without the keylog"
    );
}
