//! End-to-end TLS decryption tests against real captured sessions.
//!
//! Unlike the in-crate unit tests (which drive the crypto with synthetic
//! known-answer vectors), these run the built binary against real TLS
//! handshakes captured on loopback, decrypt them with the session's
//! SSLKEYLOGFILE, and grep a marker string that exists ONLY inside the
//! encrypted payload. That proves the whole pipeline — capture parsing,
//! stream reassembly, key derivation, record decryption — not just the
//! primitives.
//!
//! Fixtures live in `tests/fixtures/` and are regenerated by
//! `tests/fixtures/generate.sh`. Each is a throwaway localhost session to a
//! self-signed cert, so the committed keylogs protect nothing.

use std::path::PathBuf;
use std::process::Command;

fn netgrep() -> Command {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_netgrep"));
    // netgrep falls back to the SSLKEYLOGFILE env var when --keylog is absent.
    // Strip it so these tests depend only on the explicit flag — otherwise a
    // developer with SSLKEYLOGFILE exported (plausible right after running the
    // fixture generator) would decrypt in the negative control and false-fail.
    cmd.env_remove("SSLKEYLOGFILE");
    cmd
}

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Decrypt `pcap` with `keylog` and return whether `marker` was found in the
/// decrypted output (stdout carries matched payloads).
fn decrypts_to(pcap: &str, keylog: &str, marker: &str) -> bool {
    let out = netgrep()
        .arg("--keylog")
        .arg(fixture(keylog))
        .arg("-I")
        .arg(fixture(pcap))
        .arg(marker)
        .output()
        .expect("failed to run netgrep");
    assert!(
        out.status.success(),
        "netgrep exited unsuccessfully: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout).contains(marker)
}

#[test]
fn decrypts_real_tls13_session() {
    assert!(
        decrypts_to(
            "tls13_aesgcm.pcap",
            "tls13_aesgcm.keys",
            "netgrep-tls13-marker-7Qx"
        ),
        "TLS 1.3 AES-GCM session should decrypt and expose the request marker"
    );
}

#[test]
fn decrypts_real_tls12_session() {
    // Regression guard for the ServerHello-negotiation fix: this capture is a
    // client that offered TLS 1.3 but was negotiated down to 1.2 by the server
    // — the real-world shape that failed to decrypt before the fix.
    assert!(
        decrypts_to(
            "tls12_ecdhe_rsa_aesgcm.pcap",
            "tls12_ecdhe_rsa_aesgcm.keys",
            "netgrep-tls12-marker-4Rk"
        ),
        "TLS 1.2 ECDHE-RSA-AES128-GCM session should decrypt and expose the request marker"
    );
}

/// Negative control: without the keylog, `marker` must NOT appear in netgrep's
/// output, and netgrep must have actually *processed* the capture (its summary
/// line) — proving the positive tests decrypt rather than match cleartext.
///
/// We assert on the summary line instead of an exit code: netgrep does not
/// adopt grep's nonzero-on-no-match convention, and coupling to that would
/// make this silently break if it ever did — worse, an empty stdout from a
/// crash would masquerade as "marker absent" and pass.
fn assert_marker_encrypted(pcap: &str, marker: &str) {
    let out = netgrep()
        .arg("-I")
        .arg(fixture(pcap))
        .arg(marker)
        .output()
        .expect("failed to run netgrep");
    let stdout = String::from_utf8_lossy(&out.stdout);
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("packets seen"),
        "netgrep should have processed {pcap}; summary line missing.\nstderr: {stderr}"
    );
    assert!(
        !stdout.contains(marker),
        "marker must be encrypted in {pcap}; it should not be visible without the keylog"
    );
}

#[test]
fn markers_are_genuinely_encrypted() {
    // Run the control against BOTH fixtures. Without a 1.3 control, a
    // regenerated 1.3 capture that leaked its marker into an unencrypted
    // record would let decrypts_real_tls13_session pass for the wrong reason.
    assert_marker_encrypted("tls12_ecdhe_rsa_aesgcm.pcap", "netgrep-tls12-marker-4Rk");
    assert_marker_encrypted("tls13_aesgcm.pcap", "netgrep-tls13-marker-7Qx");
}
